apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rack-gold-wild
  namespace: istio-system
spec:
  secretName: rack-gold-wild
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: '*.m.rack.gold'
  dnsNames:
  - '*.m.rack.gold'
