apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: {{ .Release.Namespace }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: null@borg.dev
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - dns01:
          cloudDNS:
            # Set this to your GCP project-id
            project: coen-mahamed-ali
