apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - grafana.m.rack.gold
  gateways:
  - istio-system/rack-gold
  http:
  - route:
    - destination:
        host: monitoring-grafana
        port:
          number: 80
# ---
# apiVersion: networking.istio.io/v1alpha3
# kind: VirtualService
# metadata:
#   labels:
#     app: prometheus
#   name: prometheus
#   namespace: {{ .Release.Namespace }}
# spec:
#   hosts:
#     - prometheus.upo.one
#   gateways:
#   - istio-system/rack-gold
#   http:
#   - route:
#     - destination:
#         host: monitoring-kube-prometheus-prometheus
#         port:
#           number: 9090
