apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
  namespace: {{ .Release.Namespace }}
spec:
  limits:
  - default:
      cpu: 0.3
      memory: 512Mi
    defaultRequest:
      cpu: 0.1
      memory: 256Mi
    type: Container
