apiVersion: "security.istio.io/v1beta1"
kind: "PeerAuthentication"
metadata:
  name: "default"
  namespace: default
spec:
  mtls:
    mode: PERMISSIVE
---
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: istio-egress
  namespace: istio-system
spec:
  hosts:
  - '*.googleapis.com'
  - 'grafana.com'
  - 'raw.githubusercontent.com'
  - '*.github.com'
  location: MESH_EXTERNAL
  ports:
  - name: https
    number: 443
    protocol: HTTPS
  resolution: NONE
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: rack-gold
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http-rack-gold
      protocol: HTTP
    hosts:
    - '*.m.rack.gold'
    tls:
      httpsRedirect: true # sends 301 redirect for http requests
  - port:
      number: 443
      name: https-rack-gold
      protocol: HTTPS
    hosts:  
    - '*.m.rack.gold'
    tls:
      mode: SIMPLE 
      credentialName: rack-gold-wild
      minProtocolVersion: TLSV1_2
      maxProtocolVersion: TLSV1_3
