apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  destination:
    name: in-cluster
    namespace: cert-manager
  source:
    helm:
      releaseName: cert-manager
      valueFiles:
        - values.yaml
    path: cert-manager
    repoURL: https://github.com/borg-land/k8s-demo
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
