apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  labels:
    app: kiali
  name: kiali
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
    - kiali.m.rack.gold
  gateways:
  - istio-system/upo-prod
  http:
  - route:
    - destination:
        host: kiali
        port:
          number: 20001
